import random
stats1 = random.randint(1, 6)
stats2 = random.randint(1, 6)
stats3 = random.randint(1, 6)
stats4 = random.randint(1, 6)
stat = stats1+stats2+stats3+stats4-min(stats1, stats2, stats3, stats4)
print("Strength:", stat)

stats1 = random.randint(1, 6)
stats2 = random.randint(1, 6)
stats3 = random.randint(1, 6)
stats4 = random.randint(1, 6)
stat = stats1+stats2+stats3+stats4-min(stats1, stats2, stats3, stats4)
print("Intelligence:", stat)

stats1 = random.randint(1, 6)
stats2 = random.randint(1, 6)
stats3 = random.randint(1, 6)
stats4 = random.randint(1, 6)
stat = stats1+stats2+stats3+stats4-min(stats1, stats2, stats3, stats4)
print("Wisdom:", stat)

stats1 = random.randint(1, 6)
stats2 = random.randint(1, 6)
stats3 = random.randint(1, 6)
stats4 = random.randint(1, 6)
stat = stats1+stats2+stats3+stats4-min(stats1, stats2, stats3, stats4)
print("Dexterity:", stat)

stats1 = random.randint(1, 6)
stats2 = random.randint(1, 6)
stats3 = random.randint(1, 6)
stats4 = random.randint(1, 6)
stat = stats1+stats2+stats3+stats4-min(stats1, stats2, stats3, stats4)
print("Charisma:", stat)

stats1 = random.randint(1, 6)
stats2 = random.randint(1, 6)
stats3 = random.randint(1, 6)
stats4 = random.randint(1, 6)
stat = stats1+stats2+stats3+stats4-min(stats1, stats2, stats3, stats4)
print("Constitution:", stat)

